### ISSUE TITLE
Out of date / inconsistent information

### ISSUE THREAD

**Issue by jenkinzz** [emailmonday/Cerberus#106]
Hey there, after familiarizing myself with Cerberus' site and downloading 3.0, I saw there's a few discrepancies across the documentation and had a few questions:

- website lists "fluid, responsive, & hybrid" as the template variations but the release contains "w/ and w/o media queries" instead
- "fluid, responsive, & hybrid" exist on the top-level of the repo, and it looks like you're still updating them? I'm just mostly confused which set is the "correct" set, and I'm thinking others would be too.
- media queries are much more widely supported than the docs say, since Gmail has been rolling it out to their clients. [Source](https://litmus.com/blog/gmail-to-support-responsive-email-design).
- Does cerberus require an inliner, or not? There's a lot of inline code, but also some embedded css targeting a few classes and selectors. Looking through the issue log, people have cited inliners as helping them solve their problems

**Comment by TedGoas** [comment]
@jenkinzz Thanks great, points.

- These two versions are [archived](https://github.com/TedGoas/Cerberus/tree/master/archived-versions) and essentially deprecated. I should add some language to support this.
- Yes, those are the ones that are actively maintained.
- Good point, I haven't updated the docs since the Gmail switch.
- Another good point! I recommend against using an inliner, I should note this in the docs.

Thanks for taking a look at the docs. Not something I hear a lot about and I should be more on top of them.

**Comment by jenkinzz** [comment]
No problemo, glad I could help!

I've found myself making a framework for devs across my employer, and realized it's quite similar to yours. There's a couple of features I've implemented that I don't see in Cerberus, and I'd be happy to show you how they've been useful to me, if you're interested. I thought it might be more useful to enrich an existing solution rather than try to peddle my own.

**Comment by TedGoas** [comment]
@jenkinzz sure thing, I'd love to hear what you've been using most in your own work. Let's chat here for now. If we decide they have legs, we can create separate issues for this. Friendly reminder that the goal of Cerberus is to be "A few simple, but solid patterns."

**Comment by TedGoas** [comment]
@jenkinzz I _think_ everything above is addressed... [have a look](http://tedgoas.github.io/Cerberus/) 😀
