### ISSUE TITLE
Basic question on creating paragraphs in text

### ISSUE THREAD

**Issue by nickpish** [emailmonday/Cerberus#132]
Thank you for your work on this framework; it's the best I've found by far. Quick question: what is your recommended method for creating paragraphs of text within this structure? `<p>` tags within a `<td>` or separate `<tr>`s for each paragraph? I had always operated under the assumption that `<p>` or `<div>` tags could be stripped out by the client, and have typically created new rows for each block of text (although less markup would be preferable). Thanks for any insight.

**Comment by dyspop** [comment]
I believe in using `p` tags for paragraphs in emails. This framework supports it! https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html#L244

**Comment by nickpish** [comment]
@dyspop - thanks for the response; it looks like one needs to define margins for any paragraph spacing, not padding (Outlook doesn't seem to like the latter), no?

**Comment by dyspop** [comment]
Some versions of Outlook do not support padding, this is true. You can use `Margin` (for right, bottom and left shorthand but not top) or `margin-right`, `margin-bottom`, and `margin-left` individually. If you need margin on top... simply add it to the bottom of the preceding neighbor.

**Comment by TedGoas** [comment]
@nickpish Hey thanks! Regarding paragraphs, placing each block of text in its own `<tr><td>` is always safe. Until recently, I would code paragraphs this way:

    <tr>
        <td style="padding: 0 0 10px;">
            paragraph 1
        </td>
    </tr>
    <tr>
        <td style="padding: 0 0 10px;">
            paragraph 2
        </td>
    </tr>

This is always safe, though as you mention, requires more code.

---

It's _also_  safe to use basic semantic tags like `<h1>` and `<p>` in email, like so:

    <tr>
        <td>
            <p style="margin: 0 0 10px;">
                paragraph 1
            </p>
            <p style="margin: 0 0 10px;">
                paragraph 2
            </p>
        </td>
    </tr>

[Mark Robbins has a good post](http://blog.gorebel.com/accessibility-in-email-part-ii/) describing the current support for `<h>` and `<p>` tags in email clients. It's not always pixel perfect (some email clients remove inline styles from these tags and use their own default spacing), but this is typically what I do for running paragraphs with titles.

I'm not sure what happens when `<p>` tags are replaced with `<div>`s... worth testing.

**Comment by nickpish** [comment]
@TedGoas Great, thanks very much- I will try the `<p>` approach in my next email project.
