### ISSUE TITLE
line-heights' units

### ISSUE THREAD

**Issue by commonpike** [emailmonday/Cerberus#138]
Within the templates, line-heights are sometimes specified in px and sometimes unitless. There is a point in both of them, but it would be neat if it was consistent.

**Comment by TedGoas** [comment]
@commonpike good point, would be good to unify the `line-height` units. Have a recommendation?

**Comment by commonpike** [comment]
That was quick :-) MDN insists on unitless heights. 

https://developer.mozilla.org/en-US/docs/Web/CSS/line-height 

The reason being inheritance, which your templates are not using because most stuff is in style attributes anyway. But I would still go for unitless, so 15px / 20px becomes 15px / 1.33 .

**Comment by TedGoas** [comment]
@commonpike +1 on the MDN article, but it focuses on the web rather than email. I asked around and it seems that while unit-less is the only one that inherits properly, it's ignored by Outlook. So we'd have to include separate `mso-line-height-alt` to match up Outlook.

However it seems using `%` is universally understood in email clients. So `15px / 20px` becomes `15px / 133%`. I like this since it achieves almost the same thing as unit-less but has better support in the email world.

Whaddya think?

**Comment by commonpike** [comment]
That's good to know ! But according to MDN, 133% doesn't inherit the quite same as 1.33 does. So then you'd might as well use 15px/20px consistently, just a matter of taste.

By the way, there is another pro for using hardcoded line-heights, which is the vertical rythm of the layout. But anyway it seems you have no choice :-)

**Comment by TedGoas** [comment]
Yep, I realize 133% doesn't inherit the quite same as 1.33 does. It's unfortunate there's no single way to cascade this in email. But that's ok, we're just making `line-height` units consistent here. `px` and `%` are similar, though I prefer `%` in that the line height updates itself as the `font-size` is changed. `px` would require both to be changed.

**Comment by commonpike** [comment]
👏
