### ISSUE TITLE
DPI scaling in Outlook 2013

### ISSUE THREAD

**Issue by thomasaustin** [emailmonday/Cerberus#150]
I found adding style="margin: auto; width: 600px;" to the email container tables fixed the issue.

https://litmus.com/community/discussions/151-mystery-solved-dpi-scaling-in-outlook-2007-2013

**Comment by TedGoas** [comment]
@thomasaustin Sorry, what is the issue you are reporting here?

**Comment by TedGoas** [comment]
@thomasaustin Sorry not sure what this code does or what issue it fixes. Can you explain?

**Comment by jameswilson** [comment]
Per the [link](https://litmus.com/community/discussions/151-mystery-solved-dpi-scaling-in-outlook-2007-2013) in the OP, the issue being reported here pertains to "Fonts are blown out, tables appear crunched" in Outlook, and is caused by users who've enabled "desktop DPI scaling because of poor eyesight, or increasingly, because this is the default setting on new high DPI laptops".

**Comment by thomasaustin** [comment]
@TedGoas For some reason it was scaling the width of my email to 50%. I can't seem to replicate this with the template itself so I'm going to close this issue.
