### ISSUE TITLE
White space on both sides in gmail app in android

### ISSUE THREAD

**Issue by Damonji** [emailmonday/Cerberus#173]
First of all, say hi and thanks for this work, it's incredible what you have achieved untill now.

If I can help, for me would be a pleasure.

I have tested the hybrid template not the others, I will keep you notifed.

Still some blank pixels (about 5-10px) on both sides in gmail app on android. 

On landscape mode on Android that empty space makes 2 & 3 columns to display not correctly. Also happens with side image and text on right  & left.

can those margins be removed? Or the columns width must be reduced on all devices to fix that display issue  :-(

![screenshot_20180426-114155](https://user-images.githubusercontent.com/38752748/39298911-c6be5032-4947-11e8-9a65-dacdc458932d.jpg)
![screenshot_20180426-114134](https://user-images.githubusercontent.com/38752748/39298913-c7005fea-4947-11e8-80f0-241fb24abc97.jpg)
![screenshot_20180426-114215](https://user-images.githubusercontent.com/38752748/39298915-c729405e-4947-11e8-8c41-d8846e13720d.jpg)

**Comment by TedGoas** [comment]
Fortunately (or unfortunately, depending on how you read this), all of these behaviors are intentional.

1. Regarding the `5-10px` on either side of the email, that's part of gmail android app. Nothing we can do there. (And Gmail isn't the only email client that adds space here 😞.)

2. Regarding the column and alignment issues, appears the Gmail app you're testing [doesn't support media queries](https://emails.hteumeuleu.com/trying-to-make-sense-of-gmail-css-support-after-the-2016-update-53c15151063a), so this is hybrid design in action. The 3-column layout stacking in a triangle is a result of `min-` and `max-width`s, not media queries. Same with the "left image and right content text" example above. You can try experimenting with the `min-` and `max-width` to fill extra space.

**Comment by Damonji** [comment]
Yeah thank you, I though we could detect android gmail app and then set a width for each colum when 2 or 3 columns.

Is there anyway to detect android gmail app to change any css?

Thanks keep going!

**Comment by TedGoas** [comment]
@Damonji unfortunately there's no way to detect the android gmail app (or any gmail product) with CSS.
