### ISSUE TITLE
Full bleed background content not expanding 100% (Outlook iOS)

### ISSUE THREAD

**Issue by thomasaustin** [emailmonday/Cerberus#196]
The div within the full bleed background section isn't expanding to 100% of the parent container.

![img_0429](https://user-images.githubusercontent.com/2408813/45478429-d2a85200-b73b-11e8-9de3-f188cb3cde59.PNG)

**Comment by TedGoas** [comment]
@thomasaustin I'm _pretty_ sure this is not a bug and iOS Outlook just doesn't display emails edge to edge, but I could be wrong. I notice the almost-black background, which is the `<body>` bg color, doesn't go full bleed either.

Do you see any other emails going full bleed in iOS Outlook? Can you post a screenshot here?

**Comment by thomasaustin** [comment]
@TedGoas It's the copy/content within that isn't expanding 100%. I've swapped the div for a table tr td which seems to have fixed it (see below). 

![group](https://user-images.githubusercontent.com/2408813/45491192-03e74900-b761-11e8-8612-c8d342fc64ee.jpg)

**Comment by TedGoas** [comment]
Ooh that's no good. Thanks, I'll investigate.

**Comment by TedGoas** [comment]
@thomasaustin Sorry, I've been meaning to get to this! I did a big of digging and it seems the _width_ of that full bleed area is correct, but the whole thing is getting left-aligned instead of centered, so the width seems off.

![img_3660](https://user-images.githubusercontent.com/1172461/46377258-1f5db980-c666-11e8-8f36-c8160f6ec7db.PNG)

---

If we center the right tag, I think we can fix it that way:

![img_3661](https://user-images.githubusercontent.com/1172461/46377279-2d133f00-c666-11e8-9f45-dc88f4c4b6a0.PNG)
