### ISSUE TITLE
3-Columns not rending in mobile

### ISSUE THREAD

**Issue by miamimabel** [emailmonday/Cerberus#198]
Hello!

I am having issues with our design utilizing the "hybrid" template. 

I need to add a three-column section for buttons; however, when adding a row in the footer, the mobile version "squishes" the buttons, and in some cases, the button bleeds outside of the main container (see screenshot). I'm also adding a screenshot of the code used for that section.

Any guidance is greatly appreciated!

![email-footer-mobile jpg](https://user-images.githubusercontent.com/44374217/47386914-ed2aff00-d6db-11e8-81e9-8ab3ddfdeb81.png)
![email-footer](https://user-images.githubusercontent.com/44374217/47386925-f1571c80-d6db-11e8-947a-546806d6db7b.JPG)

**Comment by TedGoas** [comment]
Hi @miamimabel, I double-checked [the original responsive code](https://github.com/TedGoas/Cerberus/blob/master/cerberus-responsive.html) and it seems to work.

![screen shot 2018-10-23 at 9 31 52 pm](https://user-images.githubusercontent.com/1172461/47400596-d3091500-d70b-11e8-83ed-465ef64e59e1.png)

---

It's hard to reproduce your issue with a screenshot of the code (actual code is better, next time), but I noticed your images are not responsive:
![screen shot 2018-10-23 at 9 32 24 pm](https://user-images.githubusercontent.com/1172461/47400601-d8665f80-d70b-11e8-8c06-bbbd37ef5ab1.png)

**🚨 I also don't know what email client this screenshot is from... if it doesn't support media queries, the responsive template columns will not stack.** In which case, you might want to use the Hybrid Template.

But as mentioned, it's hard to look into this further without the code.

---

Since this doesn't seem to be a problem with the original source code, I'd like to close this issue. I'm happy to discuss further or help you with your code [on Stack Overflow](https://stackoverflow.com/questions/tagged/html-email).
