### ISSUE TITLE
Question regarding media queries yahoo and gmail

### ISSUE THREAD

**Issue by AlsonicTech** [emailmonday/Cerberus#216]
Is there any special trick to do any of these templates to work on yahoo and gmail web or mobile apps ?

I tried all 3 templates for this.

I just added inline font-size to p element, and it seems that it does not resize with the default `font-size: 17px !important;` for small devices.  Also tried to copy all styles inside BODY tag, and nothing changes.

I tried this on Yahoo and Gmail web browser and on Yahoo mobile app.

![IMG_7633](https://user-images.githubusercontent.com/6364236/56648795-999a6d80-668c-11e9-9c3b-12de8a82a748.PNG)

![Screenshot 2019-04-24 12 30 29](https://user-images.githubusercontent.com/6364236/56648881-c3ec2b00-668c-11e9-9601-05af34da6259.png)

**Comment by TedGoas** [comment]
There is no special trick to making these templates work out of the box in Gmail or Yahoo apps and website. I opened the **hybrid template** in Yahoo webmail on my iPhone and it displayed properly (preview below). 

**However it's important to note that [not all versions of Yahoo mail and Gmail support media queries](https://www.campaignmonitor.com/css/media-queries/media/)**, so we can't rely on styles defined in the `<style>` tag (including `@media` queries) to be applied.

I wasn't able to reproduce your screenshots above; I would double-check that your ESP is meddling with the markup. The mobile `font-size:17px;` can be overridden by applying an `!important` to your inline style (`<p style="font-size: 15px !important;">` or [by removing this rule from your template](https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html#L185).

Does that answer your questions?

---

![IMG_F88E0716AA06-1](https://user-images.githubusercontent.com/1172461/56817779-36d3de00-6814-11e9-84a3-c46f323ca711.jpeg)

**Comment by TedGoas** [comment]
@Al3xR0 Did you see my comment ☝️? Does that answer your questions?

**Comment by AlsonicTech** [comment]
@TedGoas sorry for the late reply.

The idea is that I have a mail template with huge fonts like 72px for titles (added inline with font-size css style) and when the media query reach the point of resizing, it does not work...

Just try putting big font inline on the element, and for media query put a smaller font, and see if it works.

**Comment by TedGoas** [comment]
@Al3xR0 Thanks for getting back. Here are two things to try in your case:

1. I would remove [this CSS rules](https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html#L185) from your template. It sounds like it's doing more bad than good in your case.

2. If you enlarge the font size, ensure that you [also adjust the `line-height`](https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html#L258) to keep that value in step. I bet that's what's causing the text overlap in [your screenshot above](https://user-images.githubusercontent.com/6364236/56648881-c3ec2b00-668c-11e9-9601-05af34da6259.png).

---

Since this bug focused on how you're trying to _extend_ these templates (rather than what's in this repo), I'm going to close this issue. But I'm happy to keep working with you on your use case! ✌️
