### ISSUE TITLE
Emails flagged as spam?

### ISSUE THREAD

**Issue by dan-pierce** [emailmonday/Cerberus#219]
We have recently implemented these templates for 2 different clients, and both report that their emails are going straight into spam (something we have never had a problem with previously).

All emails have sufficient content length etc, and Mailtrap reports a low spam score.

Have you encountered this before with your templates and/or know of anything in them that may cause this?

**Comment by TedGoas** [comment]
@dan-pierce Hi Dan, I haven't encountered any spam troubles with these templates. I've used them at my jobs for the last several years and never had a deliverability issue with these templates. I don't know anything in these templates that would trigger spam filters.

There are so many factors **outside of the email markup** that could lead to emails getting marked as spam. Sender reputation, sender IP address, from name, subject line, email content (text, images, links, spam trigger words), historical subscriber behavior, just to name a few. I would start my investigation there, if you haven't already.

---

Happy to keep discussing, but since this likely isn't an issue with this' repo's source, I'll close this issue.
