### ISSUE TITLE
RTL in media query breaks line breaks

### ISSUE THREAD

**Issue by htuscher** [emailmonday/Cerberus#24]
If you use the media query version of the template and you have the element with text left and image right this is achieved using table dir="rtl".

This causes the line breaks to do weird things. If the sentenced is split up it starts in the next line from the right but the next text is in the same line from the left. On OSX this is only visible with the dots of the sentence, but in Outlook this breaks the entire textblock.

**Comment by TedGoas** [comment]
@hhoechtl Thanks so much for this, Hans. I was able to replicate this (most prominent in Outlook 2007).

Since we presumably never want the actual text to display RTL, I added a few `dir="ltr"`'s in the child `<td>`'s. Seems to achieve the effect we want.

Let me know if [this commit](https://github.com/TedGoas/Cerberus/commit/d94c2409ea685d6f04503f608a19e4f2520d3e4e) solves your issue.

**Comment by htuscher** [comment]
Yes, the issue is solved
