### ISSUE TITLE
conditional statements for MSO in email body

### ISSUE THREAD

**Issue by DangerNoodl** [emailmonday/Cerberus#254]
**Describe the bug**
This is more of a question about the conditional statements for MSO that are in the body of the email than a bug. When I add text into a table, and under that table there is a blank <!--[if mso]> and a blank table
![Screen Shot 2020-12-09 at 3 46 39 PM](https://user-images.githubusercontent.com/75756680/101685444-c0f6a780-3a35-11eb-8fe0-600140d036c6.png)
, do I have to fill in the same text here that I just filled in the table above?

**To Reproduce**
1. Which template? (there are three) 
- there are examples of this in all 3 but I'm going to include a screenshot from the hybrid template
2. Which email clients and/or devices are affected? 
- MSO

**Screenshots**

**Comment by TedGoas** [comment]
@DangerNoodl 👋 So each MSO tag has an opening tag (`<!--[if mso]>`) and a closing tag (`<![endif]-->`). Anything *between* those tags will only be read by Microsoft Office (in our case, Windows Outlook 2007+).

So in the example above, we're opening a MSO-only table at the top and closing the MSO-only table towards the bottom. No other email client will read this, but they *will* read the `<table>` starting on line 314 because it's outside the `<!--[if mso]>` MSO tags`<![endif]-->`. So you don't need to fill in the same text twice because this table is read by all email clients.

Does that answer your question?

**Comment by DangerNoodl** [comment]
@TedGoas Yes, I think that answers my question! If I don't add anything to the table with the <!--[if mso]> on line 321, can I delete it from my email I'm creating?

**Comment by TedGoas** [comment]
@DangerNoodl Yea, if you're not adding content or changing/fixing the layout specifically for Windows Outlook, you can remove all the `<!--[if mso]> MSO tags <![endif]-->`

**Comment by DangerNoodl** [comment]
@TedGoas  got it! Thank you so much!

**Comment by TedGoas** [comment]
@DangerNoodl Anytime!
