### ISSUE TITLE
Gmail & Outlook adding spaces I believe between TR tags. Can't seem to resolve.

### ISSUE THREAD

**Issue by soper79** [emailmonday/Cerberus#255]
Hello. 

I am trying to convert the    2 Even Columns : BEGIN      from the Cerberus Responsive template

  From Cerberus Reponsive into a slightly different layout variation of one large image left, 4 quadrants on the right which stack on mobile.

I'm essentially trying to recreate this layout look that this target ad has.

https://photos.app.goo.gl/XJaWA7k9Z5aP8npj8

I have a version that's close but Gmail & Outlook just do not want to cooperate. Does anybody have any ideas of something I might be missing? I'd really appreciate it if so. Thanks.

Online Link at the template:
https://bit.ly/34fccVF

I suppose it's not purely on gmail & outlook as even as the view online section here is slightly off.

Images from Gmail & outlook (dark mode):
gmail
https://photos.app.goo.gl/vu5qZptok5mAQvdA6

outlook
https://photos.app.goo.gl/5RxcEfS4b2DYhT988

Experimential code block attached as text file.

[Left_Left_4_Small_Right_Responsive.txt](https://github.com/TedGoas/Cerberus/files/5705414/Left_Left_4_Small_Right_Responsive.txt)

**Comment by TedGoas** [comment]
@soper79 Since this doesn't deal with Cerberus's source code, I'm going to close this as an issue here. I don't have time to dig into your source code, but I think you're on the right track in modifying the 2 column pattern.

If they're not already, I would put the 4 300x300 images in their own `<table>` and put each image in their own `<td>`. So a 2x2 table. After that, I'd add a `display: block; line-height: 0;` to each image. My guess is you're getting some unwanted line-height below those images.

If this continues to be a problem, you'll likely get a faster answer on [Stack Overflow](https://stackoverflow.com/questions/tagged/html-email) or on the [email geeks slack](https://email.geeks.chat). ✌️
