### ISSUE TITLE
Link leads to 404 page not found

### ISSUE THREAD

**Issue by andreas-becker** [emailmonday/Cerberus#256]
https://github.com/TedGoas/Cerberus/blob/fcd0f8d42e98a4f48b484bd972f39ddd2d2faa0b/cerberus-fluid.html#L35
https://github.com/TedGoas/Cerberus/blob/fcd0f8d42e98a4f48b484bd972f39ddd2d2faa0b/cerberus-hybrid.html#L35
https://github.com/TedGoas/Cerberus/blob/fcd0f8d42e98a4f48b484bd972f39ddd2d2faa0b/cerberus-responsive.html#L35

**Comment by TedGoas** [comment]
Oh no! Thanks for flagging this, I'll find a suitable replacement.

**Comment by TedGoas** [comment]
Note to self: This is a super-specific article, might be worth it to link to [an archived version of it](https://web.archive.org/web/20190717120616/http://stylecampaign.com/blog/2015/02/webfont-support-in-email/) rather than wade through all the surface-level, click-bait-y articles tackling this subject.
