### ISSUE TITLE
error when using thunderbird for sending

### ISSUE THREAD

**Issue by Eddy2909** [emailmonday/Cerberus#32]
I got "Es ist ein Problem beim Einfügen der Datei 160.jpg in die Nachricht aufgetreten" for each image.

replacing "http://placehold.it/160" with "https://placeholdit.imgix.net/~text?txtsize=15&txt=160%C3%97160&w=160&h=160" worked.. I think Thunderbird blocks forwardings..

**Comment by TedGoas** [comment]
@Eddy2909 I haven't tried sending email from Thunderbird like this. Are you sending out final emails with the placeholder images? Or just testing the default template?

**Comment by Eddy2909** [comment]
I just tried to test and edit the default ones. I think thunderbird doesnt accept the redirection from http://placehold.it/160 to the correct picture https://placeholdit.imgix.net/~text?txtsize=15&txt=160%C3%97160&w=160&h=160.

If I use https://placeholdit.imgix.net/~text?txtsize=15&txt=160%C3%97160&w=160&h=160 it works fine. ;)

**Comment by TedGoas** [comment]
@Eddy2909 Thanks for bringing this to my attention. I wonder if it's the domain extension of the images that is giving Thunderbird a hard time. Anyway, I'm glad you found a workaround!

I'm hesitant to change the simple nature of the image code for this edge case since it's meant to be learned from and not shipped with these images in place, so I'm going to close this for now. Thank you once again for letting me know about this bug; I'll keep my eye out for anything like this going forward. If you continue to have issues with this or find another bug, please open another issue. Cheers!
