### ISSUE TITLE
Fluid-Hybrid template not displaying full-width on iPhone when sending via Constant Contact

### ISSUE THREAD

**Issue by labean365** [emailmonday/Cerberus#42]
I'm seeing an issue where the Cerberus fluid hybrid template isn't displaying full-width on iPhone Mail when sent via Constant Contact.  The email only takes up about 50% of the width of the screen, and only affects portrait mode (looks ok in landscape).

I'm tried adjusting viewport and body width, along with doctype and a few other things... but I can't seem to get it to display correctly.  Also, I'm seeing a flash/flicker where it displays full-width and then reshapes to 50%.  Any idea what might be going on here, or how to fix?  

The iPad portrait and landscape view looks good.  So far, it's only doing this for iPhones as far as I can tell.  And only when sent via Constant Contact.  I'm wondering if it's something in their footer which I can't remove?

![iphone-cerberus-constantcontact](https://cloud.githubusercontent.com/assets/15820370/12951288/a176c6f8-cfdf-11e5-83dd-fa13779bd913.PNG)

**Comment by jpmeeker** [comment]
It’s not displaying full width because of the footer that Constant Contact is adding in at send time has a specific width applied to it's containing table. This results in the media query resizing the content you’ve included but because the footer says it is a width of XXXpx iOS mail honors that width and shrinks the email accordingly. I’m not as familiar with Constant Contact as other ESP's but there should be a way for you to either remove the footer or edit it.

If you can remove the added footer I would suggest removing it as the CAN-Spam info is in the template and you don't need the constant-contact footer. If you can't remove it then you'll want to remove the CAN-Spam info from the template and edit the canned footer so that it matches your template and adapt its structure to be fluid/hybrid.

**Comment by labean365** [comment]
Thanks @meekero, 

There is no way to edit the footer code or remove it — it's a requirement of CC.  Fortunately, we were able to have customer support remove the logo/badge in the top right, but this didn't fix the issue... the white bar kicked all the way out to the right once again.

We love this template and it seems to be working with every other email client... might be time to leave Constant Contact sooner than later if we can't find a fix.

I wonder if there is a way to glean the code and override the CC width on that footer...

**Comment by labean365** [comment]
Ok quick update -- It looks like we were able to find 2 fixes to this issue:

• We added the following code to our @ media query, with much thanks to ShannonDelgado [via this post](https://community.constantcontact.com/t5/Email-Marketing/Mobile-Friendly-Footer/td-p/70895/page/2)

`body > table:last-of-type table {
    width:100% !important;
}`

•  We also called ConstantContact support and they were able to update our footer to mobile/responsive code. They mentioned the last-of-type CSS fix above wouldn't work in all email clients, but it seemed to work for us. Not sure why they don't just update this for everyone..

![iphone-cerberus-constantcontact-2](https://cloud.githubusercontent.com/assets/15820370/12960336/c2b2944a-d008-11e5-8bb7-85639b880df4.PNG)
