### ISSUE TITLE
Retina images

### ISSUE THREAD

**Issue by smallpirate** [emailmonday/Cerberus#47]
Is there a workaround, or a suggestion for displaying high-density images? In particular for 100% width images for banners etc where you have `height=""` empty. 

Usually, I would use both height and width, and load in an image that is double size:

```
<img src="http://placehold.it/1200x240/" width="600" height="120" border="0" alt=" ">
```

**Comment by TedGoas** [comment]
@jenarmstrong The height is left intentionally empty so that images scale proportionately in clients without media support. If you include a height, the full height of the image may persist as its width decreases.

You should be able to load retina images using `width` and `max-width` properties, like so:
`<img src="http://placehold.it/1200x240/" width="600" height=" " border="0" alt=" " style="width: 100%; max-width: 600px;>`

This way the image scales on narrow screens without media queries. Lemme know if that solves your issue!

**Comment by TedGoas** [comment]
@jenarmstrong Were you able to work around this issue?

**Comment by smallpirate** [comment]
Indeed I was, thank you! This ticket can now be closed.

_Jen Armstrong_
0413 416 083
www.smallpirate.com.au
