### ISSUE TITLE
Outlook 2016/Win - Issue with Button

### ISSUE THREAD

**Issue by longjasonm** [emailmonday/Cerberus#49]
Outlook 2016 was not rendering button correctly. I have written a fix here: https://gist.github.com/longjasonm/51f5dbaf88915ce4f9aca41d5a27fe15

**Comment by TedGoas** [comment]
[screenshot here](http://cl.ly/2c2m0K173k1Z)

**Comment by TedGoas** [comment]
@longjasonm I tested the Hybrid template and [the buttons pass in Litmus](https://cloud.githubusercontent.com/assets/1172461/14591301/b0e19a00-04dc-11e6-91a3-82084a749a71.png), but that looks like Outlook 2016 for Mac whereas your screenshot looks like Windows. **Is that correct?** Windows Outlook 2016 isn't included in Litmus and I don't have immediate access to a real copy, so thank you for catching this. You uncovered and fixed something that has not been previously covered!

As you noted in [your gist](https://gist.github.com/longjasonm/51f5dbaf88915ce4f9aca41d5a27fe15), the only change is adding the `<span>`. Since this is a low-risk, non-destabilizing edit, I made this change across the templates without verifying it. I verified that it doesn't break anything elsewhere.

I will leave this open until I verify Windows Outlook 2016, but I'm pretty confident in your fix. Thank you so much!

**Comment by longjasonm** [comment]
@TedGoas Maybe we are in a pilot program or something, but our instance of Litmus does have access to Outlook 2016 for Windows (see this screenshot with two "Outlook 2016" screenshots: http://cl.ly/3h0M3k1p3T2g), which is where I found the error. 

If you need to do a screencast or would like me to verify code by running a test and then making the results public, I'm happy to do so.

Thanks for making this fix! I love good solid email code and you've done a great job; glad I could contribute even a little bit 👍

**Comment by TedGoas** [comment]
@longjasonm Strange! I dug into my account settings and saw that Win Outlook 2016 wasn't enabled. I enabled it, retested, and verified. Thank you for 1. finding / fixing the bug, and 2. alerting me that I had a client disabled!

**Comment by metalgigio** [comment]
why u removed this piece of code from buttons?

`<!--[if mso]>&nbsp;&nbsp;&nbsp;&nbsp;<![endif]-->`

**Comment by TedGoas** [comment]
@metalgigio Before, most email clients would use CSS `padding` to get horizontal space, whereas Outlook would used the `&nbsp;`'s in the MSO tags. I took the `&nbsp;`'s out of the MSO conditional tags and removed the horizontal padding buttons get the same horizontal padding in every client. 

Perhaps I should not have included this change in this issue.
