### ISSUE TITLE
Strange behavior with Sparrow

### ISSUE THREAD

**Issue by systemride** [emailmonday/Cerberus#5]
This might be more of an issue with Sparrow, but in the Sparrow client this:

`body,
# bodyTable {

```
height:100% !important;
width:100% !important;
margin:0;
padding:0;
```

}`

causes the email content to "jump" as if it were a gif, and it slowly pushes the content down. It's the strangest thing ever. If you remove #bodyTable it doesn't happen. Just something to note.

**Comment by TedGoas** [comment]
@systemride Hi there, I just released a new version of Cerberus. If you're still having trouble and can recreate the same issue above with the new code, can you please file a new bug? For now, I'm going to close this issue since the code you're working with is moving towards deprecation.

If you have any questions, hit me up here or on Twitter @tedgoas.
