### ISSUE TITLE
ios mailbox not displaying properly

### ISSUE THREAD

**Issue by rmdydo** [emailmonday/Cerberus#7]
I used the default template and it looks great everywhere except on the mailbox app on ios. It seems to be stretching images to fill the device width if the image is larger than the screen instead of using the specified image or td width. I attached some images to further illustrate the issue.
Thanks
![2e058ba8-b41f-426d-8c4c-88cd034b06f3](https://cloud.githubusercontent.com/assets/899468/5672945/ca8d2682-9763-11e4-882c-b264aa817098.png)
![59fcbff3-11d2-43f7-8111-4950d6d9daa4](https://cloud.githubusercontent.com/assets/899468/5672946/ca8e74ec-9763-11e4-9f48-9dda13421e74.png)

**Comment by TedGoas** [comment]
@rmdydo Thanks for surfacing this. I'm currently working on a new release that addresses rendering Mailbox. At moment, Mailbox DOES NOT support media queries, so the goal should be get a shrunk version of the desktop email (like Gmail app).

I've seen some weird things like this appear in my own testing, def. something to keep an eye on. In the meantime, please let me know if you make any headway fixing your screens above.

**Comment by rmdydo** [comment]
@TedGoas I emailed Mailbox support and they responded that they are aware of the issue and are looking into it. So hopefully they will address the issue as it appears to be a bug with the Mailbox itself.

**Comment by TedGoas** [comment]
@rmdydo Brilliant, thanks for emailing Mailbox directly! I'm hoping they can change things on their end; their email-rendering-funkiness seems to go beyond just not supporting media queries and their updates don't seem to address email rendering.

**Comment by TedGoas** [comment]
@rmdydo Hi there, I just released a new version of Cerberus. 

I'm still working with a few issues on Mailbox with the new code but don't experience what you've described above. If you're still having trouble and can recreate the same issue above with the new code, can you please file a new bug? For now, I'm going to close this issue since the code you're working with is moving towards deprecation.

If you have any questions, hit me up here or on Twitter @tedgoas.
