### ISSUE TITLE
Update to HTML5 doctype

### ISSUE THREAD

**Issue by TedGoas** [emailmonday/Cerberus#86]
It's easy and it’s enough to trigger standards mode on supported clients. [source](https://emails.hteumeuleu.com/which-doctype-should-you-use-in-html-emails-cd323fdb793c#.h51b35q8l)

**Comment by kmedeiros** [comment]
Great! A minor problem with using the xhtml transitional doc-type is that it prohibits wrapping block-level elements with `<a></a>` tags unlike HTML 5.

This is especially helpful when wanting to wrap an image and corresponding headline with a single `<a>` tag so that ESPs don't register duplicate links in their reports. 

Similar to this: 
http://www.brucelawson.co.uk/tests/anchors-wrapping-blocks.htm
https://www.seroundtable.com/block-level-links-google-seo-16369.html

I haven't fully tested it across multiple email clients though.

It seems to be more common for folks to link the image and headline separately, or not link them at all and use a button instead. 

Curious if you have any thoughts about the technique?

**Comment by TedGoas** [comment]
@kmedeiros I haven't tested scenarios like this yet, but everything seems to either stay the same or get easier when switching from `xhtml doc-type` to `html5 doc-type`. If you test this with html5, I'd love to hear the results!
